# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# Azure Files NFS Encryption in Transit requires:
# - RHEL for SAP 8.8, 8.10, 9.x and higher
# - Microsoft packages repository
# - aznfs package

- name:                                "1.3.4 EiT - RHEL - Validate OS version meets minimum requirements"
  block:
    - name:                            "1.3.4 EiT - RHEL - Parse RHEL version"
      ansible.builtin.set_fact:
        rhel_major:                    "{{ ansible_distribution_version.split('.')[0] | int }}"
        rhel_minor:                    "{{ ansible_distribution_version.split('.')[1] | int if ansible_distribution_version.split('.') | length > 1 else 0 | int }}"

    - name:                            "1.3.4 EiT - RHEL - Validate version requirements"
      when:                            (rhel_major | int < 8) or
                                       (rhel_major | int == 8 and rhel_minor | int not in [8, 10])
      ansible.builtin.fail:
        msg: |
                                       Azure Files NFS Encryption in Transit requires:
                                       - RHEL 8.8, 8.10, or
                                       - RHEL 9.0 and higher
                                       Current version: {{ ansible_distribution }} {{ ansible_distribution_version }}

- name:                                "1.3.4 EiT - RHEL - Download Microsoft GPG Public Key"
  ansible.builtin.get_url:
    url:                               "https://packages.microsoft.com/keys/microsoft.asc"
    dest:                              "/tmp/microsoft.asc"
    mode:                              '0644'
  register:                            ms_key_download
  retries:                             4
  delay:                               30
  until:                               ms_key_download is succeeded

- name:                                "1.3.4 EiT - RHEL - Add Microsoft GPG Public Key"
  become:                              true
  become_user:                         root
  ansible.builtin.rpm_key:
    state:                             present
    key:                               /tmp/microsoft.asc
  register:                            ms_key_import

- name:                                "1.3.4 EiT - RHEL - Download Latest Microsoft GPG Public Key"
  ansible.builtin.get_url:
    url:                               "https://packages.microsoft.com/keys/microsoft-2025.asc"
    dest:                              "/tmp/microsoft-2025.asc"
    mode:                              '0644'
  register:                            ms_latest_key_download
  retries:                             4
  delay:                               30
  until:                               ms_latest_key_download is succeeded

- name:                                "1.3.4 EiT - RHEL - Add Microsoft GPG Public Key"
  become:                              true
  become_user:                         root
  ansible.builtin.rpm_key:
    state:                             present
    key:                               /tmp/microsoft-2025.asc
  register:                            ms_latest_key_import

# - name:                                "1.3.4 EiT - RHEL - Download Microsoft packages repository RPM"
#   ansible.builtin.get_url:
#     url:                               "https://packages.microsoft.com/config/rhel/{{ ansible_distribution_version.split('.')[0] }}/packages-microsoft-prod.rpm"
#     dest:                              "/tmp/packages-microsoft-prod.rpm"
#     mode:                              '0644'
#   register:                            ms_repo_download
#   retries:                             4
#   delay:                               30
#   until:                               ms_repo_download is succeeded

- name:                                "1.3.4 EiT - RHEL - Install Microsoft packages repository"
  ansible.builtin.dnf:
    name:                              "https://packages.microsoft.com/config/rhel/{{ ansible_distribution_version.split('.')[0] }}/packages-microsoft-prod.rpm"
    state:                             present
  register:                            ms_repo_install

# - name:                                "1.3.4 EiT - RHEL - Update dnf cache"
#   ansible.builtin.dnf:
#     update_cache:                      true
#   when:                                ms_repo_install is changed
#   changed_when:                        false

- name:                                "1.3.4 EiT - RHEL - Install aznfs package"
  ansible.builtin.dnf:
    name:                              aznfs
    state:                             present
  register:                            aznfs_install

# - name:                                "1.3.4 EiT - RHEL - Cleanup temporary repository RPM"
#   ansible.builtin.file:
#     path:                              "/tmp/packages-microsoft-prod.rpm"
#     state:                             absent

- name:                                "1.3.4 EiT - RHEL - Display installation result"
  ansible.builtin.debug:
    msg:
      - "Microsoft repository installed: {{ ms_repo_install is changed }}"
      - "aznfs package installed: {{ aznfs_install is changed }}"
    verbosity: 2
